<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="viewport" content="width=device-width" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Campaign Update</title>
</head>

<body itemscope itemtype="http://schema.org/EmailMessage">

<table class="body-wrap">
  <tr>
    <td></td>
    <td class="container" width="600">
      <div class="content">
        <table class="main" width="100%" cellpadding="0" cellspacing="0">
          <tr>
            <td class="alert alert-info">
              New Features Added
            </td>
          </tr>
          <tr>
            <td class="content-wrap">
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td class="content-block">
                    <p>Since the project was initially launched, the following features have been added:</p>
                    <ul>
                      <li>Server Side email validation from <a href="https://documentation.mailgun.com/api-email-validation.html">https://documentation.mailgun.com/api-email-validation.html</a></li>
                      <li>Responsive transactional HTML email templates from <a href="https://github.com/mailgun/transactional-email-templates">https://github.com/mailgun/transactional-email-templates</a></li>
                      <li>Support for sending bulk email through Mailgun. Great for post launch notifications (it powers this email)</li>
                    </ul>
                  </td>
                </tr>
                <tr>
                  <td class="content-block">
                    <a href="https://github.com/mailgun/node-prelaunch" class="btn-primary">Fork this on Github</a>
                  </td>
                </tr>
                <tr>
                  <td class="content-block">
                    <a href="https://github.com/mailgun/node-prelaunch">&mdash; Node Prelaunch App</a>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
        <div class="footer">
          <table width="100%">
            <tr>
              <td class="aligncenter content-block">Don't like these annoying emails? <a href="%unsubscribe_url%">Unsubscribe</a></td>
            </tr>
          </table>
        </div></div>
    </td>
    <td></td>
  </tr>
</table>

</body>
</html>